(()=>{if(window.__SAFARI_LAYOUT_V19_READY__)return;window.__SAFARI_LAYOUT_V19_READY__=true;
const root=document.documentElement,vv=window.visualViewport;let raf;
const cfg=[['comodinesModal','.folder-window'],['cronogramaModal','.schedule-window'],['archivoModal','.archivo-window'],['itemEditorModal','.item-editor-window'],['profileEditorModal','.profile-editor-window'],['exportPasswordModal','.export-password-window'],['scoreModal','.score-window'],['scorePasswordModal','.score-password-window'],['sanctionsModal','.sanctions-window'],['sanctionEditorModal','.sanction-editor-window'],['leadersModal','.leaders-window'],['leaderEditorModal','.leader-editor-window'],['comodinEditorModal','.comodin-editor-window'],['mapModal','.map-window'],['mapPointEditorModal','.map-point-editor-window']];
function vp(){return{w:Math.max(280,Math.round(vv?.width||innerWidth||document.documentElement.clientWidth)),h:Math.max(300,Math.round(vv?.height||innerHeight||document.documentElement.clientHeight))}}
function vars(){const{x,...r}= {x:0,...vp()},w=r.w,h=r.h;root.style.setProperty('--legacy-vw',w+'px');root.style.setProperty('--legacy-vh',h+'px');const a=document.querySelector('#archivoModal .archivo-header');if(a)root.style.setProperty('--v19-archivo-header-h',Math.ceil(a.getBoundingClientRect().height)+'px');const s=document.querySelector('#sanctionsModal .sanctions-header');if(s)root.style.setProperty('--v19-sanctions-header-h',Math.ceil(s.getBoundingClientRect().height)+'px')}
function refit(){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{vars();if(document.getElementById('mapModal')?.classList.contains('open'))window.dispatchEvent(new Event('resize'))})}
function reset(m,sel){const w=m.querySelector(sel);if(w){w.scrollTop=0;w.scrollLeft=0}m.querySelectorAll('.comodines-list,.schedule-days,.archivo-window,.league-table-wrap,.sanctions-window,.leaders-groups,.map-sidebar,.map-search-results').forEach(e=>{e.scrollTop=0;e.scrollLeft=0})}
function opened(m,sel){vars();reset(m,sel);[0,60,180,360].forEach(t=>setTimeout(refit,t))}
function wire(m,sel){if(!m||m.dataset.viewportFitV19==='1')return;m.dataset.viewportFitV19='1';let was=m.classList.contains('open');new MutationObserver(()=>{const o=m.classList.contains('open');if(o&&!was)opened(m,sel);was=o}).observe(m,{attributes:true,attributeFilter:['class']});if(was)opened(m,sel)}
function all(){cfg.forEach(([id,sel])=>wire(document.getElementById(id),sel))}
document.addEventListener('focusin',e=>{const t=e.target;if(!(t instanceof HTMLElement)||!t.closest('.item-editor-modal.open,.profile-editor-modal.open,.export-password-modal.open,.score-password-modal.open,.sanction-editor-modal.open,.leader-editor-modal.open,.comodin-editor-modal.open,.map-point-editor-modal.open'))return;setTimeout(()=>{vars();t.scrollIntoView({block:'center',inline:'nearest',behavior:'smooth'})},120)});
vv?.addEventListener('resize',refit,{passive:true});vv?.addEventListener('scroll',vars,{passive:true});addEventListener('resize',refit,{passive:true});addEventListener('orientationchange',()=>{setTimeout(refit,80);setTimeout(refit,350)},{passive:true});addEventListener('pageshow',()=>{vars();all()});new MutationObserver(all).observe(document.body,{childList:true,subtree:true});vars();all()})();